---
apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "safe.fullname" . }}-cfg-env

data:
  PYTHONDONTWRITEBYTECODE: "true"
  SECRET_KEY: "insecure_key_for_dev"
  DEBUG: "true"
  ROOT_LOG_LEVEL: "DEBUG"
  #
  # NGINX_HOST_PORT: 8080
  NGINX_ENVSUBST_OUTPUT_DIR: "/etc/nginx/"
  DOCKER_NGINX_VOLUME_ROOT: "/nginx"
  #
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_NAME: postgres
  POSTGRES_HOST: {{ include "safe.fullname" . }}-cfg-db
  POSTGRES_PORT: "5432"
  DOCKER_WEB_VOLUME: ".:/app"
  #
  GUNICORN_WEB_RELOAD: "false"
  GUNICORN_BIND_PORT: "8001"
  GUNICORN_BIND_SOCKET: "unix:/nginx/gunicorn.socket"
  #
  DJANGO_SUPERUSER_PASSWORD: admin
  DJANGO_SUPERUSER_USERNAME: root
  DJANGO_SUPERUSER_EMAIL: test@example.com
  DJANGO_OTP_ADMIN: "false"
  DJANGO_ALLOWED_HOSTS: "*"
  #
  DEFAULT_FILE_STORAGE: django.core.files.storage.FileSystemStorage
  FORCE_SCRIPT_NAME: "/cfg/"
  CSRF_TRUSTED_ORIGINS: "http://localhost:8000"
  MEDIA_URL: "http://localhost:8000/cfg/media/"
  #
  CGW_URL: http://{{ include "safe.fullname" . }}-nginx:8000/cgw
  CGW_FLUSH_TOKEN: {{ .Values.tokens.common_token_1 }}