apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "safe.fullname" . }}-ui-env

data:
  ### Required variables ###
  NEXT_PUBLIC_INFURA_TOKEN: ""
  NEXT_PUBLIC_GATEWAY_URL_PRODUCTION: http://localhost:8000/cgw

  # infura token used by Safe Apps
  NEXT_PUBLIC_SAFE_APPS_INFURA_TOKEN: ""

  # Transaction simulation
  NEXT_PUBLIC_TENDERLY_SIMULATE_ENDPOINT_URL: ""
  NEXT_PUBLIC_TENDERLY_PROJECT_NAME: ""
  NEXT_PUBLIC_TENDERLY_ORG_NAME: ""

  # Flag to switch to the production environment (redirect urls, gateway url, etc)
  NEXT_PUBLIC_IS_PRODUCTION: "true"

  ### Optional variables ###
  # These variables are required only if you require a certain feature in the interface (e.g. Portis wallet)
  # Or overwrite the fallback values (set a different WalletConnect bridge)

  # Latest supported safe version, used for upgrade prompts
  NEXT_PUBLIC_SAFE_VERSION: "1.3.0"

  # Access keys
  NEXT_PUBLIC_SENTRY_DSN: ""
  NEXT_PUBLIC_BEAMER_ID: ""

  # Wallet specific variables
  NEXT_PUBLIC_WC_PROJECT_ID: {{ .Values.wallets.wallet_connect_project_id }}
  NEXT_PUBLIC_WC_BRIDGE: {{ .Values.wallets.wallet_connect_bridge }}
  NEXT_PUBLIC_FORTMATIC_KEY: ""
  NEXT_PUBLIC_PORTIS_KEY: ""
  NEXT_PUBLIC_CYPRESS_MNEMONIC: ""

  NEXT_PUBLIC_GATEWAY_URL_STAGING: ""

  # sets the listener only for localhost
  REVERSE_PROXY_UI_PORT: '8080'
