{{- $releaseName := .Release.Name }} # define the local var here

{{- range $chain, $chainValues := .Values.chains }}
{{ if $chainValues.enabled }}
---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ $releaseName }}-{{ $chainValues.network_name | lower }}-txs-rabbitmq

spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $releaseName }}-{{ $chainValues.network_name | lower }}-txs-rabbitmq
  template:
    metadata:
      labels:
        app: {{ $releaseName }}-{{ $chainValues.network_name | lower }}-txs-rabbitmq
    spec:
      containers:
        - name: {{ $chainValues.network_name | lower }}-txs-rabbitmq
          image: rabbitmq:3.11.26-management
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: guest # Notice: change it if you'd like
            - name: RABBITMQ_DEFAULT_PASS
              value: guest # Notice: change it if you'd like
          ports:
            - name: rabbit-ui
              containerPort: 15672

{{- end }} # if
{{- end }} # range