name: Python CI
on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  test-app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Check docker compose valid
      run: |
        cp .env.sample .env
        docker compose pull
